"""Resolve a project's template into an isolated editable worktree.

This is the ``copyroom template-checkout`` workflow plus the answers/source
helpers reused by render-test and preview. The template is never edited in
place: a git worktree on a scratch branch is created (cloning remote sources
into a cache first) so the agent's edits don't disturb the template's main
checkout, and nothing is ever pushed.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

import yaml

from .._compat import gitutil
from .._compat.errors import CopyRoomError
from .._compat.state_machine import StateMachine
from .model import (
    VALID_CHECKOUT_TRANSITIONS,
    CheckoutStatus,
    TemplateCheckout,
)

__all__ = [
    "CopyRoomError",
    "checkout_template",
    "discard_template_edit",
    "read_answers",
    "resolve_project_root",
]

_checkout_sm = StateMachine(VALID_CHECKOUT_TRANSITIONS, entity_name="TemplateCheckout")


# ---------------------------------------------------------------------------
# Project + answers
# ---------------------------------------------------------------------------


def resolve_project_root(project_root: str | Path | None) -> Path:
    """Resolve *project_root* (defaulting to the cwd) to an absolute path."""
    if project_root is None:
        return Path.cwd().resolve()
    return Path(project_root).resolve()


def read_answers(project_root: Path) -> dict:
    """Read ``.copier-answers.yml`` from *project_root* as a mapping.

    Raises ``CopyRoomError`` when the file is missing, unreadable, or not a
    mapping — this is also how we confirm we're standing in a Copier project.
    """
    answers_file = project_root / ".copier-answers.yml"
    if not answers_file.is_file():
        raise CopyRoomError(
            "No .copier-answers.yml here — template commands must run from a "
            "project generated by Copier/CopyRoom.",
            state="not_started",
        )
    try:
        with open(answers_file) as f:
            data = yaml.safe_load(f)
    except (yaml.YAMLError, OSError) as exc:
        raise CopyRoomError(
            f"Failed to read .copier-answers.yml: {exc}",
            state="not_started",
        ) from exc
    if not isinstance(data, dict):
        raise CopyRoomError(
            ".copier-answers.yml is not a mapping.",
            state="not_started",
        )
    return data


# ---------------------------------------------------------------------------
# Source resolution + caching
# ---------------------------------------------------------------------------


def _cache_root() -> Path:
    """Root of the template clone/worktree cache (overridable for tests)."""
    override = os.environ.get("COPYROOM_CACHE_DIR")
    if override:
        return Path(override) / "templates"
    base = os.environ.get("XDG_CACHE_HOME") or str(Path.home() / ".cache")
    return Path(base) / "copyroom" / "templates"


def _template_cache_dir(source: str) -> Path:
    digest = hashlib.sha256(source.encode()).hexdigest()[:16]
    return _cache_root() / digest


def _project_slug(project_root: Path) -> str:
    digest = hashlib.sha256(str(project_root).encode()).hexdigest()[:12]
    return digest


def _edit_paths(project_root: Path, source: str) -> tuple[Path, str, Path]:
    """Compute the (cache_dir, branch, worktree_dir) for *project_root*'s edit.

    The single definition of where the edit worktree/branch live, shared by
    :func:`checkout_template` and :func:`discard_template_edit` so they always
    agree on the slug-derived names.
    """
    cache_dir = _template_cache_dir(source)
    slug = _project_slug(project_root)
    branch = f"copyroom/edit/{slug}"
    worktree_dir = cache_dir / f"wt-{slug}"
    return cache_dir, branch, worktree_dir


def _ensure_local_repo(source: str, cache_dir: Path) -> Path:
    """Return a local git repo for *source*, cloning remote sources into cache."""
    if gitutil.looks_remote(source):
        repo = cache_dir / "repo"
        if repo.is_dir():
            gitutil.fetch(repo)
        elif not gitutil.clone(source, repo):
            raise CopyRoomError(
                f"Failed to clone template source: {source}",
                state="source_resolved",
            )
        return repo

    path = Path(source).resolve()
    if not path.is_dir():
        raise CopyRoomError(
            f"Template source path not found: {source}",
            state="source_resolved",
        )
    if not gitutil.is_git_repo(path):
        raise CopyRoomError(
            f"Template at {source} is not a git repository. "
            "Previewing updates needs a git template (the edited version must "
            "live on a ref). Initialise the template repo and retry.",
            state="source_resolved",
        )
    return path


# ---------------------------------------------------------------------------
# Checkout workflow
# ---------------------------------------------------------------------------


def checkout_template(
    project_root: str | Path | None = None,
    from_ref: str | None = None,
) -> TemplateCheckout:
    """Resolve this project's template into an isolated editable worktree.

    Returns the ``TemplateCheckout`` entity in ``worktree_ready`` (with
    ``worktree_dir`` and ``branch`` populated) or ``failed``. The agent edits
    files under ``worktree_dir``; nothing touches the template's main checkout.
    """
    root = resolve_project_root(project_root)
    checkout = TemplateCheckout(project_root=root)

    answers = read_answers(root)
    source = answers.get("_src_path")
    if not source:
        checkout.status = _checkout_sm.transition(
            CheckoutStatus.initiated, CheckoutStatus.failed,
        )
        raise CopyRoomError(
            "No _src_path in .copier-answers.yml; cannot locate the template.",
            state="initiated",
        )

    checkout.template_source = str(source)
    commit = answers.get("_commit")
    checkout.previous_ref = str(commit) if commit is not None else None
    checkout.status = _checkout_sm.transition(
        CheckoutStatus.initiated, CheckoutStatus.source_resolved,
    )

    cache_dir, branch, worktree_dir = _edit_paths(root, str(source))
    repo = _ensure_local_repo(str(source), cache_dir)
    checkout.repo_dir = repo

    base = from_ref or gitutil.default_branch(repo) or "HEAD"
    checkout.base_ref = base

    if worktree_dir.is_dir() and gitutil.is_git_repo(worktree_dir):
        # Reusing a worktree from a prior session — surface any commits left on
        # the edit branch beyond its base so an abandoned edit doesn't silently
        # resurface. `template-discard` resets it.
        ahead = gitutil.commits_ahead(repo, branch, base)
        if ahead:
            checkout.reused_commits = ahead
    elif not gitutil.worktree_add(repo, worktree_dir, branch, base):
        checkout.status = _checkout_sm.transition(
            CheckoutStatus.source_resolved, CheckoutStatus.failed,
        )
        raise CopyRoomError(
            f"Failed to create an editable worktree for {source}.",
            state="source_resolved",
        )

    checkout.worktree_dir = worktree_dir
    checkout.branch = branch
    checkout.status = _checkout_sm.transition(
        CheckoutStatus.source_resolved, CheckoutStatus.worktree_ready,
    )
    return checkout


def discard_template_edit(project_root: str | Path | None = None) -> Path | None:
    """Remove this project's edit worktree + branch, resetting the edit loop.

    Resolves the same worktree/branch :func:`checkout_template` would and removes
    them (``git worktree remove --force`` + ``git branch -D``) so a subsequent
    ``template-checkout`` starts fresh from the base. A missing worktree is a
    friendly no-op (returns ``None``); otherwise returns the removed worktree
    path. Nothing in the real project tree is touched.
    """
    root = resolve_project_root(project_root)

    answers = read_answers(root)
    source = answers.get("_src_path")
    if not source:
        raise CopyRoomError(
            "No _src_path in .copier-answers.yml; cannot locate the template.",
            state="not_started",
        )

    cache_dir, branch, worktree_dir = _edit_paths(root, str(source))

    # Resolve the repo the worktree/branch live in (local source = the path
    # itself; remote = the cache clone). If neither the repo nor the worktree
    # exists, there is nothing to discard.
    if gitutil.looks_remote(str(source)):
        repo = cache_dir / "repo"
    else:
        repo = Path(str(source)).expanduser().resolve()

    if not (worktree_dir.is_dir() or gitutil.branch_exists(repo, branch)):
        return None

    if worktree_dir.is_dir():
        gitutil.worktree_remove(repo, worktree_dir)
    gitutil.delete_branch(repo, branch)
    return worktree_dir
